version: "3.8"

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis:7.2.4-alpine3.19
    container_name: redis
    restart: always
    command: redis-server
    ports:
      - 6379:6379
